lib/login.dart, lib/signup.dart, test/login_test.dart, test/signup_test.dart
=> added test files

lib/addphoto.dart, lib/addvideo.dart, lib/main.dart, lib/memoryhome.dart, lib/startup.dart
For reviewers:
- check if add photo displays thumbnail
- check if add video displays thumbnail
=> Access videos

lib/addphoto.dart, lib/creatememory.dart, lib/firebase/authentication_service.dart, lib/firebase/firestore_service.dart, lib/login.dart, lib/main.dart
- retrieves user's memories from Firestore and displays it on the home page when the user logs in
closes #36
=> Add memory

ios/Podfile.lock, lib/addphoto.dart, lib/addvideo.dart, lib/creatememory.dart, lib/firebase/authentication_service.dart, lib/firebase/firestore_service.dart, lib/main.dart, lib/memoryhome.dart, lib/startup.dart, pubspec.lock, pubspec.yaml
- add photo takes the photo and adds it to Firebase Storage
- add video takes the video and adds it to Firebase Storage (same workflow as add photo but not verified since I don't have any videos on my simulator)
closes #37
=> Add moment

lib/signup.dart
still need to refactor the authentication feature
=> fixed bug - closes #53

lib/editphoto.dart, lib/firebase/firestore_service.dart, lib/main.dart, lib/memoryhome.dart, lib/startup.dart
- successfully edits a photo moment (updating either the photo, description, or both)
- updates Firestore and Storage data
- adds appBar to editphoto.dart
=> Issue #41 - Edit Photo Moment

lib/firebase/firestore_service.dart, lib/memoryhome.dart
- deletes a moment from a memory in the app
- deletes moment doc from Firestore
- deletes moment file from Cloud Storage
=> Issue #41 - delete moment

lib/creatememory.dart, lib/editmemory.dart, lib/editphoto.dart, lib/firebase/firestore_service.dart, lib/memoryhome.dart
added functions to edit or delete a memory
*Side note: when editing a memory title, the user doesn't see the update title until they go back to the app home page. May need to open another story in the future to resolve this issue
closes #41
=> Issue #41 - edit delete memory

lib/creatememory.dart, lib/firebase/firestore_service.dart
Closes #54
Requires users to select a photo as the thumbnail for a new memory.
=> Issue #54: Memory-Thumbnail

lib/firebase/authentication_service.dart, lib/settings.dart, pubspec.lock
=> Issue #76 - logout button

lib/constants/textSizeConstants.dart, lib/login.dart, lib/memory_example.dart, lib/memoryhome.dart, lib/settings.dart, lib/signup.dart, lib/startup.dart, lib/widgets/memoryslider.dart, pubspec.lock
- adjust button ratio on start up, log in, and sign up
- adjust text size of title on start up
link #87
=> Issue #87 -  text size

lib/main.dart
Let me know how it looks on iPhone.
=> Issue #93: Centered toggle switch

lib/addphoto.dart, lib/creatememory.dart, lib/editphoto.dart, lib/memoryhome.dart
=> Moment-Clean-up

lib/firebase/authentication_service.dart
Please check with iPhone to see if the overflow is still present, I checked on iPad and it should be fine
=> Issue #95 - Fixed bug overflow in signup page

lib/firebase/authentication_service.dart, lib/login.dart, lib/tutorial.dart
=> Issue #82 - Finished email verification workflow

lib/navigation.dart
the original nav bar style did not take font size for some reason.
=> Issue #99: Responsive nav bar

ios/Podfile.lock, lib/settings.dart, pubspec.lock
closes #96 
The persistent bottom navbar should disappear after user logs out through the settings page
=> Issue #96: removed navbar after logout

lib/editvideo.dart, lib/memoryhome.dart
=> Edit-Video

lib/addphoto.dart, lib/addvideo.dart, lib/creatememory.dart, lib/editmemory.dart, lib/editphoto.dart, lib/login.dart, lib/progressReport.dart, lib/signup.dart
=> Progress report message and disabling save button across app until functions are completed

android/app/build.gradle, ios/Podfile.lock, lib/constants/routeConstants.dart, lib/firebase/authentication_service.dart, lib/forgotpassword.dart, lib/login.dart, lib/main.dart, lib/startup.dart, pubspec.lock
closes #83 
Completed forgot password feature within the account workflow
=> Issue #83 - Forgot Password feature completed

ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, lib/addphoto.dart, lib/addvideo.dart, lib/editphoto.dart, lib/editvideo.dart, lib/firebase/firestore_service.dart, lib/memoryhome.dart, pubspec.lock, pubspec.yaml
WHEN TESTING, MAKE A NEW MEMORY!!!
check for the following:
- add new memory
- add photo
- add video
- edit photo
- edit video
- edit memory
- delete moment
- delete memory
closes #110
=> Issue 110: Fix video thumbnail

lib/firebase/firestore_service.dart, lib/main.dart
=> Memory view counter

lib/main.dart
=> Lock rotation

android/app/build.gradle, android/app/google-services.json, ios/Runner.xcodeproj/project.pbxproj, ios/Runner/GoogleService-Info.plist, ios/Runner/Info.plist, pubspec.yaml
Sets up publishing on android and allows me to run the app on my iPhone. You guys will need to edit the apple ID info to run it on your iPhones. Closes #94
=> Publishing v2

lib/creatememory.dart, lib/editmemory.dart, pubspec.lock, pubspec.yaml
=> Issue #132: Date Pickers

lib/firebase/firestore_service.dart, lib/progressReport.dart, pubspec.lock
=> Issue #129 - overall rememberance rate

lib/changepassword.dart, lib/constants/textSizeConstants.dart, lib/firebase/authentication_service.dart, lib/forgotpassword.dart, lib/login.dart, pubspec.lock
=> Issue #120 - Styling and Validator for Forgot/Change Password Completed

lib/addaudio.dart, lib/editaudio.dart, lib/editvideo.dart
=> Moment: Disable button when pressed until function complete and add loading icon

lib/creatememory.dart, lib/editmemory.dart, lib/startup.dart, pubspec.lock
Let me know if I should change the format of the date (even though it's harder than I thought)
=> Issue #151: date check

lib/widgets/audioplayer.dart, pubspec.lock, pubspec.yaml
Added current position, duration, and slider
=> Issue #147: Audio UI

lib/main.dart
=> 158 cancel button for caregiver pin

ios/Podfile.lock, lib/firebase/firestore_service.dart, lib/memory.dart, pubspec.lock, pubspec.yaml
Okay sooo in order to get the dot indictor to work, I need to use setState in the onPageChanged in the CarouselSlider. But that wasn't working before (the pages got stuck) and I figured out it was because we were loading the memories in a StreamBuilder.
So I had to change the way we were getting the memories and I finally found a way to get the memories using a function I made in FirestoreService. I think this cleans up the code quite a bit and it looks much easier to read. Definitely take a look at the code and let me know if you have any questions with the changes.
- changed slider to non-looping
- added dot indicator on the bottom
closes #165
=> Issue #165: story mode add moment indicator

ios/Podfile.lock, lib/creatememory.dart, lib/editmemory.dart, lib/main.dart, lib/memorydetails.dart, pubspec.lock
Maybe we can update the view counter once they click on view and enter the slider? Thoughts?
closes #164
=> Issue #164: story mode add intro to memory

lib/firebase/firestore_service.dart, lib/progressReport.dart, pubspec.yaml
=> Moment-Type-Breakdown

lib/constants/textSizeConstants.dart, lib/firebase/firestore_service.dart, lib/memory.dart, lib/progressReport.dart
=> Issue: #168 story mode display no moments
